builds:
    -
      main: ./cmd/mnd/main.go
      binary: mnd
      goos:
        - windows
        - darwin
        - linux
      goarch:
        - amd64
      ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.buildTime={{.Date}}`.

archive:
    format: tar.gz
    format_overrides:
        - goos: windows
          format: zip
